# .github/workflows/main.yml

name: Github Pages Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: sterlingwes/gh-pages-deploy-action@v1.3
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          source-directory: public
          auto-install: no
          build-command: echo "No build"
